name: Test
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        name: Test
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - run: git fetch --tags origin
          
          - name: Get previous tag
            id: previoustag
            uses: 'WyriHaximus/github-action-get-previous-tag@v1'
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
